# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('method', models.CharField(max_length=16)),
                ('status', models.SmallIntegerField()),
                ('referrer', models.URLField()),
                ('response', models.BinaryField(null=True)),
            ],
        ),
    ]
