# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('method', models.CharField(default='get', max_length=16)),
                ('status', models.SmallIntegerField(default=0)),
                ('referrer', models.URLField()),
                ('response_content', models.BinaryField(null=True)),
                ('traceback', models.TextField(default='')),
            ],
        ),
    ]
