# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipo', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('''
CREATE FUNCTION ipo_job_on_insert() RETURNS trigger AS $$
DECLARE
BEGIN
  PERFORM pg_notify('ipo_job_insert', CAST(NEW.id AS text));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER ipo_job_on_insert_trigger 
    AFTER INSERT ON ipo_job FOR EACH ROW EXECUTE PROCEDURE ipo_job_on_insert(); 


CREATE FUNCTION ipo_job_on_done() RETURNS trigger AS $$
DECLARE
BEGIN
  PERFORM pg_notify(concat('ipo_job_done_', replace(CAST(NEW.id AS text), '-', '')), CAST(NEW.id AS text));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER ipo_job_on_done_trigger 
    AFTER UPDATE ON ipo_job FOR EACH ROW EXECUTE PROCEDURE ipo_job_on_done(); 
    
          
        ''')
    ]
